//! Create or regenerate the user-visible `.gruff-rs.yaml` configuration.
//!
//! Generated settings mirror the rule registry and retain safe family seeds.
//! The retired secret-preview key is always emitted as an inert empty list.

use crate::cli::{FailThreshold, InitArgs, OutputWriter};
use crate::config::{DeepScanBudget, DEFAULT_ABBREVIATIONS, SCHEMA_VERSION};
use crate::rules::{builtin_registry, RuleDefinition, RuleRegistry};
use crate::Severity;
use std::collections::BTreeMap;
use std::fs;
use std::io::{IsTerminal, Write};
use std::path::Path;
use std::process::ExitCode;

const DEFAULT_CONFIG_FILE: &str = ".gruff-rs.yaml";

const HEADER: &str = "\
# gruff-rs default configuration.
#
# Generated by `gruff-rs init` from the built-in rule registry.
# Rule ids and metadata can be discovered with `gruff-rs rules`.
# Per-rule thresholds and severities can be tuned in place; see the
# README for the full configuration shape (deepScanBudget, paths, allowlists, rules,
# custom_rules, exclude, sensitiveExclusions).
#
# For an existing project, run `gruff-rs analyse --generate-baseline`
# to accept today's findings as the starting point.
";

const DEFAULT_IGNORE_PATTERNS: &[&str] = &[
    ".agents/**",
    ".claude/**",
    ".codex/**",
    ".github/**",
    ".goat-flow/**",
    "target/**",
    "node_modules/**",
    "**/Cargo.lock",
    "**/package-lock.json",
    "**/yarn.lock",
    "**/pnpm-lock.yaml",
];

/// Generate the user's default config on stdout or at the requested path.
/// Existing ignores and severity choices survive `--force`; write failures return exit 2 with a practical diagnostic.
pub(crate) fn run_init(args: InitArgs, writer: OutputWriter) -> ExitCode {
    let output = &args.output;
    let preserved_ignores = read_existing_ignore_patterns(output);
    let preserved_min_severity = read_existing_minimum_severity(output);
    let preserved_deep_scan_budget = read_existing_deep_scan_budget(output);
    let body = render_default_config_with_budget(
        &builtin_registry(),
        &preserved_ignores,
        &preserved_min_severity,
        &preserved_deep_scan_budget,
    );

    // `--stdout` lets the user preview or redirect config without changing a project file.
    if args.stdout {
        writer.emit_unconditional(&body);
        return ExitCode::SUCCESS;
    }

    // An existing file is protected unless the user explicitly chose `--force`.
    if !args.force && output.exists() {
        eprintln!(
            "gruff-rs: refusing to overwrite existing {}; pass --force to replace it",
            output.display()
        );
        return ExitCode::from(2);
    }

    // A write can fail when the selected folder is read-only or the file was removed during the command.
    if let Err(error) = fs::write(output, &body) {
        eprintln!("gruff-rs: unable to write {}: {error}", output.display());
        return ExitCode::from(2);
    }

    writer.emit_unconditional(&format!(
        "Wrote default config to {}\nRun `gruff-rs analyse --generate-baseline` to accept today's findings as the starting point.",
        output.display()
    ));
    ExitCode::SUCCESS
}

/// Offer first-run config setup for analysis, summary, report, and dashboard commands.
/// A missing project root means there is nowhere safe to create the user's config.
pub(crate) fn prompt_for_command(
    project_root: Option<&Path>,
    config_override: Option<&Path>,
    no_config: bool,
    no_interaction: bool,
) {
    // Only a resolved project root gives the prompt a predictable destination to show the user.
    if let Some(root) = project_root {
        prompt_when_config_missing(root, config_override, no_config, no_interaction);
    }
}

/// Prompt to create `.gruff-rs.yaml` only during an interactive first run with no config choice.
/// Declining or using non-interactive flags leaves the user's project unchanged.
pub(crate) fn prompt_when_config_missing(
    project_root: &Path,
    config_override: Option<&Path>,
    no_config: bool,
    no_interaction: bool,
) {
    let target = project_root.join(DEFAULT_CONFIG_FILE);
    // Existing config choices or a non-interactive session mean the user should see no setup prompt.
    if !should_offer_init(&target, config_override, no_config, no_interaction) {
        return;
    }
    // A response other than `y` or `yes` means the user declined the file change.
    if !should_write_default_config(project_root) {
        return;
    }
    write_default_config_at(&target);
}

/// Decide whether the current command may show the first-run config prompt.
/// False means config already exists, the user chose config behavior, or the terminal cannot answer safely.
fn should_offer_init(
    target: &Path,
    config_override: Option<&Path>,
    no_config: bool,
    no_interaction: bool,
) -> bool {
    // Explicit config and interaction choices always override the automatic setup prompt.
    if no_config || config_override.is_some() || no_interaction {
        return false;
    }
    // An existing destination means setup is complete and must not be overwritten by a prompt.
    if target.exists() {
        return false;
    }
    std::io::stdin().is_terminal() && std::io::stderr().is_terminal()
}

/// Ask whether the user wants a default config and accept only an explicit affirmative response.
/// Input failure behaves like a decline so an interrupted terminal never creates a file.
fn should_write_default_config(project_root: &Path) -> bool {
    let mut stderr = std::io::stderr();
    let _ = write!(
        stderr,
        "No {DEFAULT_CONFIG_FILE} found in {}. Generate one with `gruff-rs init`? [y/N] ",
        project_root.display()
    );
    let _ = stderr.flush();

    // The response starts empty because only text entered after the prompt can authorize the file.
    let mut response = String::new();
    // Closed stdin or a terminal read failure means the user did not authorize config creation.
    if std::io::stdin().read_line(&mut response).is_err() {
        return false;
    }
    matches!(response.trim().to_ascii_lowercase().as_str(), "y" | "yes")
}

/// Write a confirmed first-run config and report the outcome in the terminal UI.
/// Failures stay non-panicking because a permission change can occur after the user accepts the prompt.
fn write_default_config_at(target: &Path) {
    let mut stderr = std::io::stderr();
    let preserved_ignores = read_existing_ignore_patterns(target);
    let preserved_min_severity = read_existing_minimum_severity(target);
    let preserved_deep_scan_budget = read_existing_deep_scan_budget(target);
    match fs::write(
        target,
        render_default_config_with_budget(
            &builtin_registry(),
            &preserved_ignores,
            &preserved_min_severity,
            &preserved_deep_scan_budget,
        ),
    ) {
        Ok(()) => {
            let _ = writeln!(stderr, "Wrote {}", target.display());
            let _ = writeln!(
                stderr,
                "Run `gruff-rs analyse --generate-baseline` to accept today's findings as the starting point."
            );
        }
        Err(error) => {
            // For example, the user may accept setup just before the destination directory becomes read-only.
            let _ = writeln!(
                stderr,
                "gruff-rs: unable to write {}: {error}",
                target.display()
            );
        }
    }
}

/// Render a complete default config from the live rule registry and settings preserved from an existing file.
/// Empty preserved collections produce clean defaults, while every registered rule remains visible for user editing.
#[cfg(test)]
pub(crate) fn render_default_config(
    registry: &RuleRegistry,
    extra_ignores: &[String],
    preserved_min_severity: &BTreeMap<String, FailThreshold>,
) -> String {
    render_default_config_with_budget(
        registry,
        extra_ignores,
        preserved_min_severity,
        &DeepScanBudget::default(),
    )
}

fn render_default_config_with_budget(
    registry: &RuleRegistry,
    extra_ignores: &[String],
    preserved_min_severity: &BTreeMap<String, FailThreshold>,
    deep_scan_budget: &DeepScanBudget,
) -> String {
    // Rendering begins empty so every visible line comes from the current registry and preserved user settings.
    let mut out = String::new();
    out.push_str(HEADER);
    out.push('\n');

    append_schema_version_section(&mut out);
    append_minimum_severity_section(&mut out, preserved_min_severity);
    append_deep_scan_budget_section(&mut out, deep_scan_budget);
    append_paths_section(&mut out, extra_ignores);
    append_allowlists_section(&mut out);
    append_sensitive_exclusions_section(&mut out);

    out.push_str("rules:\n");
    // Every registered rule appears in generated config so users can discover and tune it in one place.
    for definition in registry.definitions() {
        append_rule_entry(&mut out, definition);
    }

    out
}

fn append_deep_scan_budget_section(out: &mut String, budget: &DeepScanBudget) {
    out.push_str("# Bound only deep Rust analysis; text-level safety and size checks still run.\n");
    out.push_str("# CLI --deep-scan-budget LINES:BYTES|off overrides this block.\n");
    out.push_str("deepScanBudget:\n");
    out.push_str(&format!("  enabled: {}\n", budget.enabled));
    out.push_str(&format!("  maxLines: {}\n", budget.max_lines));
    out.push_str(&format!("  maxBytes: {}\n\n", budget.max_bytes));
}

/// Append the schema value that tells the loader how to interpret the generated user config.
fn append_schema_version_section(out: &mut String) {
    out.push_str(&format!("schemaVersion: {SCHEMA_VERSION}\n\n"));
}

/// Append command exit thresholds, preserving values the user already selected.
/// Missing values remain commented examples so they do not override binary defaults.
fn append_minimum_severity_section(out: &mut String, preserved: &BTreeMap<String, FailThreshold>) {
    out.push_str("# failOn controls per-subcommand fail thresholds.\n");
    out.push_str("# Uncomment and edit to override the binary defaults. Valid values:\n");
    out.push_str("# none, advisory, warning, error. CLI --fail-on flag overrides this block.\n");
    out.push_str("failOn:\n");
    append_minimum_severity_entry(out, "analyse", preserved.get("analyse"), "advisory");
    append_minimum_severity_entry(out, "report", preserved.get("report"), "none");
    out.push('\n');
}

/// Append one active preserved threshold or one commented default example.
/// `None` means the user had no value to preserve for this command.
fn append_minimum_severity_entry(
    out: &mut String,
    command: &str,
    preserved: Option<&FailThreshold>,
    placeholder: &str,
) {
    match preserved {
        // A preserved value remains active after the user regenerates config.
        Some(value) => out.push_str(&format!("  {command}: {}\n", value.as_str())),
        // No preserved value leaves a commented example rather than silently changing command behavior.
        None => out.push_str(&format!("  # {command}: {placeholder}\n")),
    }
}

/// Append built-in discovery ignores plus unique patterns preserved from the user's existing config.
/// An empty preserved list leaves only the safe generated defaults.
fn append_paths_section(out: &mut String, extra_ignores: &[String]) {
    out.push_str("paths:\n");
    out.push_str("  # Discovery-time do-not-read patterns. Use this for generated\n");
    out.push_str("  # build/vendor artifacts; use `gruff-rs analyse --generate-baseline`\n");
    out.push_str("  # or top-level `exclude` entries for accepted findings.\n");
    out.push_str("  ignore:\n");
    let mut emitted: Vec<&str> =
        Vec::with_capacity(DEFAULT_IGNORE_PATTERNS.len() + extra_ignores.len());
    // Default patterns protect users from scanning generated, vendor, and agent-control files.
    for pattern in DEFAULT_IGNORE_PATTERNS {
        // Duplicate defaults are omitted so generated config stays predictable and readable.
        if !emitted.contains(pattern) {
            emitted.push(pattern);
            out.push_str(&format!("    - {}\n", yaml_string(pattern)));
        }
    }
    // Existing project-specific ignores are appended after the portable defaults.
    for pattern in extra_ignores {
        let entry = pattern.as_str();
        // A repeated user pattern adds no behavior and would make regenerated config noisy.
        if !emitted.contains(&entry) {
            emitted.push(entry);
            out.push_str(&format!("    - {}\n", yaml_string(entry)));
        }
    }
    out.push('\n');
}

/// Append user-editable naming seeds and the inert legacy preview key.
/// New configs show the only preview value the strict loader accepts: `[]`.
fn append_allowlists_section(out: &mut String) {
    out.push_str("allowlists:\n");
    out.push_str(
        "  # acceptedAbbreviations controls which short names naming.short-variable permits.\n",
    );
    out.push_str(
        "  # This configured list replaces (not merges) built-ins; keep these seeds and\n",
    );
    out.push_str("  # append project vocabulary below.\n");
    out.push_str("  acceptedAbbreviations:\n");
    // Every family seed remains visible so users know which short names work immediately.
    for abbreviation in DEFAULT_ABBREVIATIONS {
        out.push_str(&format!("    - {abbreviation}\n"));
    }
    out.push('\n');
}

/// Append the commented sensitive-data suppression section so users can discover and copy it.
/// The section ships commented out because every entry must be written and reviewed by hand.
fn append_sensitive_exclusions_section(out: &mut String) {
    out.push_str("# sensitiveExclusions suppresses reviewed sensitive-data findings, and only\n");
    out.push_str("# those. Each entry names one exact sensitive-data rule id, one project-\n");
    out.push_str("# relative path, an optional symbol, and a required reason; every entry\n");
    out.push_str("# reports its own suppressed count in `suppressions[]` and on text output.\n");
    out.push_str("# Write entries by hand: gruff-rs never converts a reported marker or preview\n");
    out.push_str("# into one, and no message- or value-matching key is accepted here.\n");
    out.push_str("# sensitiveExclusions:\n");
    out.push_str("#   - rule: sensitive-data.aws-access-key\n");
    out.push_str("#     path: tests/fixtures/aws-sample.env\n");
    out.push_str(
        "#     reason: Synthetic key used by the loader fixture; not a live credential.\n",
    );
    out.push('\n');
}

/// Append one rule's description, enabled state, and supported numeric options for user editing.
/// A missing threshold means the rule exposes no threshold or severity controls in generated config.
fn append_rule_entry(out: &mut String, definition: &RuleDefinition) {
    out.push_str(&format!("  # {}\n", definition.description));
    out.push_str(&format!("  {}:\n", definition.id));
    // The generated boolean mirrors whether users receive this rule without changing config.
    out.push_str(&format!(
        "    enabled: {}\n",
        if definition.default_enabled {
            "true"
        } else {
            "false"
        }
    ));
    // Threshold-capable rules show both numeric and severity controls because the loader validates them as a pair.
    if let Some(threshold) = definition.threshold {
        out.push_str(&format!(
            "    threshold: {}\n",
            format_threshold(threshold.default)
        ));
        out.push_str(&format!(
            "    severity: {}\n",
            severity_name(definition.default_severity)
        ));
    }
}

/// Return the stable lowercase severity label written to user config.
fn severity_name(severity: Severity) -> &'static str {
    match severity {
        Severity::Advisory => "advisory",
        Severity::Warning => "warning",
        Severity::Error => "error",
    }
}

/// Format whole-number thresholds without a decimal while preserving fractional user-visible values.
fn format_threshold(value: f64) -> String {
    // Finite whole values are easier for users to read as integers in generated YAML.
    if value.fract() == 0.0 && value.is_finite() {
        format!("{}", value as i64)
    } else {
        format!("{value}")
    }
}

/// Quote and escape one generated YAML scalar only when its text could change meaning.
fn yaml_string(value: &str) -> String {
    // YAML-sensitive values need quotes so the user's path is loaded exactly as displayed.
    if needs_quoting(value) {
        format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
    } else {
        value.to_string()
    }
}

// YAML indicators, map separators, and comment markers can change an unquoted path's meaning in the user's generated config.
const YAML_LEADING_INDICATORS: &[char] = &['*', '&', '?', '|', '>', '!', '%', '@', '`'];

/// Decide whether a generated YAML value needs quotes to survive a user reload unchanged.
fn needs_quoting(value: &str) -> bool {
    let starts_with_indicator = value
        .chars()
        .next()
        .is_some_and(|first| YAML_LEADING_INDICATORS.contains(&first));
    starts_with_indicator || value.contains(": ") || value.contains(" #")
}

/// Read path ignores that should survive `gruff-rs init --force` regeneration.
/// Missing, unreadable, malformed, or absent list data becomes empty so users can still repair the file.
pub(crate) fn read_existing_ignore_patterns(path: &Path) -> Vec<String> {
    // No readable YAML means there are no safe existing ignore values to preserve.
    let Some(value) = read_existing_yaml(path, "ignore preservation") else {
        return Vec::new();
    };
    value
        .get("paths")
        .and_then(|paths| paths.get("ignore"))
        .and_then(|ignore| ignore.as_sequence())
        .map(|seq| {
            seq.iter()
                .filter_map(|entry| entry.as_str().map(str::to_string))
                .collect()
        })
        .unwrap_or_default()
}

/// Read valid command thresholds that should survive `gruff-rs init --force` regeneration.
/// Missing or invalid entries are skipped so the user can repair a partly broken config.
pub(crate) fn read_existing_minimum_severity(path: &Path) -> BTreeMap<String, FailThreshold> {
    // No readable YAML means there are no safe threshold overrides to preserve.
    let Some(value) = read_existing_yaml(path, "minimumSeverity preservation") else {
        return BTreeMap::new();
    };
    value
        .get("failOn")
        .and_then(|v| v.as_mapping())
        .map(|mapping| mapping.iter().filter_map(parse_preserved_entry).collect())
        .unwrap_or_default()
}

/// Preserve a valid existing deep-scan budget during `init --force` regeneration.
/// Invalid members fall back independently so regeneration can repair a broken file.
fn read_existing_deep_scan_budget(path: &Path) -> DeepScanBudget {
    let Some(value) = read_existing_yaml(path, "deepScanBudget preservation") else {
        return DeepScanBudget::default();
    };
    let Some(mapping) = value
        .get("deepScanBudget")
        .and_then(serde_yaml::Value::as_mapping)
    else {
        return DeepScanBudget::default();
    };
    let defaults = DeepScanBudget::default();
    let enabled = mapping
        .get(serde_yaml::Value::from("enabled"))
        .and_then(serde_yaml::Value::as_bool)
        .unwrap_or(defaults.enabled);
    let max_lines = preserved_positive_usize(mapping, "maxLines").unwrap_or(defaults.max_lines);
    let max_bytes = preserved_positive_usize(mapping, "maxBytes").unwrap_or(defaults.max_bytes);
    DeepScanBudget {
        enabled,
        max_lines,
        max_bytes,
        override_state: "config",
    }
}

fn preserved_positive_usize(mapping: &serde_yaml::Mapping, key: &str) -> Option<usize> {
    mapping
        .get(serde_yaml::Value::from(key))
        .and_then(serde_yaml::Value::as_u64)
        .and_then(|value| usize::try_from(value).ok())
        .filter(|value| *value > 0)
}

/// Parse one supported preserved threshold, returning `None` for entries the generated UI cannot honor.
fn parse_preserved_entry(
    (key, value): (&serde_yaml::Value, &serde_yaml::Value),
) -> Option<(String, FailThreshold)> {
    let command = key.as_str()?;
    // Only commands with a severity gate have a meaningful value to preserve.
    if !matches!(command, "analyse" | "report") {
        return None;
    }
    let threshold: FailThreshold = value.as_str()?.parse().ok()?;
    Some((command.to_string(), threshold))
}

/// Read an existing YAML file for best-effort setting preservation during regeneration.
/// `None` means the file is absent, unreadable, or malformed; malformed YAML also gives the user a repair warning.
fn read_existing_yaml(path: &Path, purpose: &str) -> Option<serde_yaml::Value> {
    // A missing destination is a normal first-run state with nothing to preserve.
    if !path.exists() {
        return None;
    }
    let content = fs::read_to_string(path).ok()?;
    match serde_yaml::from_str(&content) {
        Ok(value) => Some(value),
        Err(error) => {
            // For example, a user may leave an unclosed quote while invoking `init --force` to repair the config.
            let _ = writeln!(
                std::io::stderr(),
                "gruff-rs: could not parse existing {} for {purpose} ({error}); proceeding with defaults only",
                path.display()
            );
            None
        }
    }
}
